In [1]:
import pandas as pd

excel_file = "movies.xls"

In [2]:
movies = pd.read_excel(excel_file) # automatically only scans the first sheet

In [3]:
movies.head()

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 1,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score
0,Intolerance: Love's Struggle Throughout the Ages,1916,Drama|History|War,NaN,USA,Not Rated,123,1.33,385907.0,NaN,...,436,22,9.0,481,691,1,10718,88,69.0,8.0
1,Over the Hill to the Poorhouse,1920,Crime|Drama,NaN,USA,NaN,110,1.33,100000.0,3000000.0,...,2,2,0.0,4,0,1,5,1,1.0,4.8
2,The Big Parade,1925,Drama|Romance|War,NaN,USA,Not Rated,151,1.33,245000.0,NaN,...,81,12,6.0,108,226,0,4849,45,48.0,8.3
3,Metropolis,1927,Drama|Sci-Fi,German,Germany,Not Rated,145,1.33,6000000.0,26435.0,...,136,23,18.0,203,12000,1,111841,413,260.0,8.3
4,Pandora's Box,1929,Crime|Drama|Romance,German,Germany,Not Rated,110,1.33,NaN,9950.0,...,426,20,3.0,455,926,1,7431,84,71.0,8.0

In [6]:
movies_sheet1 = pd.read_excel(excel_file, sheet_name=0, index_col=0) # first sheet from that excel file
movies_sheet1.tail()

,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,Director,...,Facebook Likes - Actor 1,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score
Title,,,,,,,,,,,,,,,,,,,,,
Twin Falls Idaho,1999,Drama,English,USA,R,111,1.85,500000.0,985341.0,Michael Polish,...,980,505,482.0,3166,180,0,3479,87,54.0,7.3
Universal Soldier: The Return,1999,Action|Sci-Fi,English,USA,R,83,1.85,24000000.0,10431220.0,Mic Rodgers,...,2000,577,485.0,4024,401,0,24216,162,75.0,4.1
Varsity Blues,1999,Comedy|Drama|Romance|Sport,English,USA,R,106,1.85,16000000.0,52885587.0,Brian Robbins,...,23000,255,35.0,23369,0,0,35312,267,67.0,6.4
Wild Wild West,1999,Action|Comedy|Sci-Fi|Western,English,USA,PG-13,106,1.85,170000000.0,113745408.0,Barry Sonnenfeld,...,10000,4000,582.0,15870,0,2,129601,648,85.0,4.8
Wing Commander,1999,Action|Adventure|Sci-Fi,English,USA,PG-13,100,2.35,30000000.0,11576087.0,Chris Roberts,...,811,586,362.0,2497,858,3,14747,338,85.0,4.1

In [7]:
movies_sheet1.head(5).to_excel("5movies.xlsx") # to_excel method belongs to the dataframe
movies_sheet1.head(5).to_json("5movies.json")
movies_sheet1.head(5).to_csv("5movies.csv")